[project]
name = "risearch-pipeline"
version = "0.1.0"
description = "Pipeline for the analysis of the results of the RIsearch project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy", "polars", "typer", "viennaRNA"]

[project.scripts]
gw = "RIsearch_pipeline.cli:entrypoint"
risearch-pipeline = "RIsearch_pipeline.cli:entrypoint"

[dependency-groups]
dev = ["pre-commit", "pytest", "ruff"]

[tool.pytest]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.uv]
package = true
